version: 0.2

env:
  shell: bash
artifacts:
  files:
    - imagetag.txt
phases:
  install:
    on-failure: ABORT
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf -o rustup.sh https://sh.rustup.rs
      - chmod +x rustup.sh
      - ./rustup.sh -y --profile default --default-toolchain stable-aarch64-unknown-linux-gnu
      - export PATH="${HOME}/.cargo/bin:${PATH}"
  build:
    on-failure: ABORT
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY_URL
      - aws --region us-east-1 ecr-public get-login-password | docker login --username AWS --password-stdin public.ecr.aws
      - export PATH="${HOME}/.cargo/bin:${PATH}"
      - cargo fmt --check
      - cargo clippy --all-features -- -D warnings
      - cargo test --all-features
      - export IMAGE_TAG=$(date -u +%Y%m%dT%H%M%S)
      - echo "$IMAGE_TAG" > imagetag.txt
      - docker buildx build --platform linux/arm64 -f Dockerfile -t "${ECR_REGISTRY_URL}:${IMAGE_TAG}" --push .
      - echo "Pushed ${ECR_REGISTRY_URL}:${IMAGE_TAG}"
