name: LambdaDeploy

on:
  push:
    branches:
      - main
      - dev
      - prod
  pull_request_target:
    branches:
      - main
      - dev
      - prod
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: "aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu"
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run formatting check.
        run: cargo fmt --check
      - name: Run clippy check.
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test --all-targets --all-features
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 60
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ vars.REGION }}
      AWS_DEFAULT_REGION: ${{ vars.REGION }}
    steps:
      - name: Check variables
        shell: bash
        run: |
          if [[ -z "${{ vars.REGION }}" ]]; then
            echo "REGION is not set"
            exit 1
          fi;
          if [[ -z "${{ secrets.ROLE_ARN }}" ]]; then
            echo "ROLE_ARN is not set"
            exit 1
          fi;
          if [[ -z "${{ vars.ECR_REGISTRY_URL }}" ]]; then
            echo "ECR_REGISTRY_URL is not set"
            exit 1
          fi;
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
      - uses: actions/checkout@v4
      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ vars.ECR_REGISTRY_URL }}
          aws --region us-east-1 ecr-public get-login-password | docker login --username AWS --password-stdin public.ecr.aws
          export IMAGE_TAG=$(date -u +%Y%m%dT%H%M%S)
          docker buildx create --platform linux/amd64,linux/arm64 --name multiplatform --use
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t "${{ vars.ECR_REGISTRY_URL }}:$IMAGE_TAG" --push .
          echo "Pushed ${{ vars.ECR_REGISTRY_URL }}:$IMAGE_TAG"
