name: LambdaDeploy

on:
  push:
    branches:
      - main
      - dev
      - prod
  pull_request_target:
    branches:
      - main
      - dev
      - prod
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:            
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: "aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu"
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run formatting check.
        run: cargo fmt --check
      - name: Run clippy check.
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test --all-targets --all-features
